### ISSUE TITLE
showed snippets should be full examples

### ISSUE THREAD

**Issue by edublancas** [ploomber/dash-mui#4]
our examples only show the component but don't show the `@callback`, we should instead display a fully functional snippet so users can copy it, store it as `app.py`, run it with `python app.py` and see it working.

**Comment by bowang-ynd** [comment]
If we show the full code example with which users can copy it, and store it as `app.py`, run it with `python app.py`, like below:
![image](https://github.com/user-attachments/assets/bbf89afa-5e10-4484-9318-66d73e68ceff)

It would be too many lines of code and not specifying the code itself. We can refer to examples in FastAPI and highlight the code section, like below:
![image](https://github.com/user-attachments/assets/d9698bd3-8010-4c4e-8ba6-5c80e65e9b12)


For now, I will add the callback function to the code snippet display.
